# Makefile: A standard Makefile for main.c

CFLAGS = `pkg-config --cflags libavutil libavformat libswscale libavcodec`
LDLIBS = `pkg-config --libs libavutil libavformat libswscale libavcodec`

all  : main
clean:
	/bin/rm -rf main main.o 
# END OF FILE
