# Makefile: A standard Makefile for main.c

#CPPFLAGS = -I/usr/include/libxml2
LDLIBS = -lv4l2

all  : main
run:
	LD_LIBRARY_PATH=/opt/maple2021/bin.X86_64_LINUX ./main
clean:
	/bin/rm -rf main main.o
# END OF FILE
